# Enable validating this file
version: ~> 1.0

language: python
python:
    - "3.9"
sudo: false
cache:
    directories:
        - "~/.platformio"

jobs:
  include:
    - install:
      - pip install -U platformio
      - platformio upgrade
      script: ./build_platformio.sh